include device/qcom/msm8960/BoardConfig.mk

TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := true
BOARD_KERNEL_PAGESIZE = 2048
BOARD_KERNEL_SPARESIZE = 64

ifneq (,$(wildcard vendor/qcom/sawara/kernel))
TARGET_PREBUILT_KERNEL := vendor/qcom/sawara/kernel
BOARD_KERNEL_BASE := 200000
TARGET_NO_KERNEL := false
BOARD_KERNEL_CMDLINE := androidboot.hardware=sawara
endif

TARGET_USERIMAGES_USE_EXT4 := true

BOARD_EGL_CFG := device/qcom/msm8960/egl.cfg

BOARD_BOOTIMAGE_PARTITION_SIZE := 1572864
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1287651328
BOARD_USERDATAIMAGE_PARTITION_SIZE := 2147483648
BOARD_PERSISTIMAGE_PARTITION_SIZE := 16777216
BOARD_CACHEIMAGE_PARTITION_SIZE := 262144000
BOARD_FLASH_BLOCK_SIZE := 131072 # BOARD_KERNEL_PAGE_SIZE * 64

# hack to prevent llvm from building
BOARD_USE_QCOM_LLVM_CLANG_RS := true

BOARD_HAS_ATH_WLAN := true

WPA_SUPPLICANT_VERSION := VER_2_0_DEV
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_HOSTAPD_DRIVER        := NL80211
CONFIG_DRIVER_NL80211 := y
WIFI_DRIVER_MODULE_PATH := "/system/wifi/ath6kl_sdio.ko"
WIFI_DRIVER_MODULE_NAME := "ath6kl_sdio"
WIFI_SDIO_IF_DRIVER_MODULE_PATH := "/system/wifi/cfg80211.ko"
WIFI_SDIO_IF_DRIVER_MODULE_NAME := "cfg80211"

WIFI_TEST_INTERFACE     := "sta"
WIFI_DRIVER_FW_PATH_STA := "sta"
WIFI_DRIVER_FW_PATH_AP  := "ap"
WIFI_DRIVER_FW_PATH_P2P := "p2p"
